### ISSUE TITLE
Support markdown formatting

### ISSUE THREAD

**Issue by konradmoesch** [yukibtc/ntfy-sdk#3]
ntfy supports markdown formatting: [https://docs.ntfy.sh/publish/#markdown-formatting](https://docs.ntfy.sh/publish/#markdown-formatting)
If a message is sent in markdown format and the Markdown header is set, it will be displayed correctly. It would be great if this crate supports this

**Comment by yukibtc** [comment]
Hi, sorry for the late reply. I just added `markdown` support. I'm going to publish v0.4.0
